server:
  port: 8090
spring:
  application:
    name: querydsl
  datasource:
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mysql-test
  jpa:
    hibernate:
      ddl-auto: create