version: '3'
services:
  test-db: # 서비스이름
    image: mysql:5.7  # 이미지
    container_name: mysql-test   # 컨테이너 이름
    ports:
      - "3307:3306"   # 포트 설정  외부:내부
    environment:
      MYSQL_ROOT_PASSWORD: 1111   # 패스워드설정
      MYSQL_DATABASE: mysql-test
    volumes:
      - ./mysql/:/var/lib/mysql/
    command:
      - --character-set-server=utf8mb4      # 인코딩
      - --collation-server=utf8mb4_unicode_ci
      - --skip-ssl
      - --lower_case_table_names=1
      - --explicit_defaults_for_timestamp
      - --sql_mode=IGNORE_SPACE
      - --max_connections=10000
      - --wait_timeout=60000